_wandb:
    value:
        cli_version: 0.25.1
        e:
            ufllxf0dnmfrtvkzgqiaherulif25dsk:
                codePath: report\section_2.4.py
                codePathLocal: section_2.4.py
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "180007989248"
                        used: "169765605376"
                email: ma24m018@smail.iitm.ac.in
                executable: C:\Users\Ganga Sharan\AppData\Local\Programs\Python\Python313\python.exe
                git:
                    commit: 7548e42a1e3a4d9083dd7e08f17c0cb2a1ba2eca
                    remote: https://github.com/Neha-irongirl/da6401_assignment_2
                host: LAPTOP-BQBRQ1PT
                memory:
                    total: "12593659904"
                os: Windows-11-10.0.26200-SP0
                program: C:\Users\Ganga Sharan\OneDrive\dl_project\da6401_assignment_2\report\section_2.4.py
                python: CPython 3.13.3
                root: C:\Users\Ganga Sharan\OneDrive\dl_project\da6401_assignment_2\report
                startedAt: "2026-04-12T09:29:45.543765Z"
                writerId: ufllxf0dnmfrtvkzgqiaherulif25dsk
        m: []
        python_version: 3.13.3
        t:
            "1":
                - 1
                - 80
            "2":
                - 1
                - 80
            "3":
                - 2
                - 13
                - 16
            "4": 3.13.3
            "5": 0.25.1
            "8":
                - 3
            "12": 0.25.1
            "13": windows-amd64
first_layer:
    value: features[0] - Conv2d(3,64)
image:
    value: saint_bernard_98
last_layer:
    value: features[27] - ReLU after last Conv
section:
    value: "2.4"
